//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public string MemberId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyWebsite { get; set; }
        public string Location { get; set; }
        public string ContactPerson { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
