//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int ContactUsId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string SenderEmailId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
