//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonCompanySharing
    {
        public int ShareindId { get; set; }
        public string MemberId { get; set; }
        public string SharedEmail { get; set; }
        public Nullable<int> ResumeId { get; set; }
        public Nullable<System.DateTime> SharedOn { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Resume Resume { get; set; }
    }
}
