//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patent
    {
        public int Id { get; set; }
        public string MemberId { get; set; }
        public string PatentTitle { get; set; }
        public Nullable<System.DateTime> PatentDate { get; set; }
        public string PatentDescription { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
