//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public string MemberId { get; set; }
        public Nullable<int> IsLookingForJob { get; set; }
        public string PreferredSkills { get; set; }
        public string PreferredLocation { get; set; }
        public string PreferredDesignation { get; set; }
        public string CurrentLocation { get; set; }
        public Nullable<int> IsReadyToReallocate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
