//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public string MemberId { get; set; }
        public string ProjectTitle { get; set; }
        public string Technologies { get; set; }
        public string Tools { get; set; }
        public string Ownerr { get; set; }
        public string Role { get; set; }
        public string TeamSIze { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
