//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandler.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public int Id { get; set; }
        public string MemberId { get; set; }
        public string CertificateTitle { get; set; }
        public string Organization { get; set; }
        public string GradeRank { get; set; }
        public string AreaOfExpertise { get; set; }
        public Nullable<System.DateTime> DateOfCertification { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
