//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandler.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbresumebuilderEntities : DbContext
    {
        public dbresumebuilderEntities()
            : base("name=dbresumebuilderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Certification> Certifications { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Copyright> Copyrights { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Experience> Experiences { get; set; }
        public virtual DbSet<Hobby> Hobbies { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<NonCompanySharing> NonCompanySharings { get; set; }
        public virtual DbSet<Patent> Patents { get; set; }
        public virtual DbSet<PersonalInformation> PersonalInformations { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<PublicProfile> PublicProfiles { get; set; }
        public virtual DbSet<Resume> Resumes { get; set; }
        public virtual DbSet<ResumeSection> ResumeSections { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<TemplateSection> TemplateSections { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<Referral> Referrals { get; set; }
        public virtual DbSet<Sharing> Sharings { get; set; }
    }
}
