//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandler.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Id { get; set; }
        public string MemberId { get; set; }
        public string NameOfSchoolCollege { get; set; }
        public string Qualification { get; set; }
        public string Location { get; set; }
        public string EducationBoard { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
