//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandler.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int Id { get; set; }
        public string MemberId { get; set; }
        public string Language1 { get; set; }
        public Nullable<int> ReadProficiency { get; set; }
        public Nullable<int> WriteProficiency { get; set; }
        public Nullable<int> SpeakProficiency { get; set; }
        public Nullable<int> IsNative { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
