//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandler.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resume()
        {
            this.NonCompanySharings = new HashSet<NonCompanySharing>();
            this.ResumeSections = new HashSet<ResumeSection>();
        }
    
        public int ResumeId { get; set; }
        public string MemberId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> DownloadCount { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string PublicUrl { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<int> PublicSharingType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> TemplateId { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NonCompanySharing> NonCompanySharings { get; set; }
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResumeSection> ResumeSections { get; set; }
    }
}
