//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandler.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeSection
    {
        public int ResumeSectionId { get; set; }
        public Nullable<int> ResumeId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<int> SectionOrder { get; set; }
    
        public virtual Resume Resume { get; set; }
        public virtual TemplateSection TemplateSection { get; set; }
    }
}
