//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandler.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int Id { get; set; }
        public string MemberId { get; set; }
        public string Skill1 { get; set; }
        public Nullable<int> Proficiency { get; set; }
        public string Certifications { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
