//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandler.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateSection()
        {
            this.ResumeSections = new HashSet<ResumeSection>();
        }
    
        public int SectionId { get; set; }
        public Nullable<bool> AllowReorder { get; set; }
        public Nullable<bool> AllowSelection { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string SectionName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResumeSection> ResumeSections { get; set; }
        public virtual Template Template { get; set; }
    }
}
